# 5G Adversarial IDS - Baseline Configuration
# Configuration for baseline Random Forest training

# Data configuration
data:
  processed_dir: "data/processed"
  raw_dir: "data/raw"
  
# Baseline model configuration
baseline:
  model_type: "RandomForest"
  
  # Hyperparameters for Random Forest
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
    n_jobs: -1
    
  # Feature engineering
  feature_engineering:
    apply_pca: true
    n_components: 7
    standardize: true
    
  # Cross-validation settings
  cross_validation:
    enabled: true
    cv_folds: 5
    random_state: 42

# Model storage configuration
models:
  save_dir: "models"
  
# Output configuration
output:
  base_dir: "results"
  save_predictions: true
  save_probabilities: true
  generate_plots: true
  
# Logging configuration
logging:
  level: "INFO"
  save_logs: true
