# 5G Adversarial IDS - Evaluation Configuration
# Configuration for comprehensive system evaluation

# Data configuration
data:
  processed_dir: "data/processed"
  raw_dir: "data/raw"

# Evaluation configuration
evaluation:
  # Models to evaluate
  models: ["baseline", "robust"]
  
  # Model paths (auto-detected if not specified)
  model_paths:
    baseline: "models/rf_baseline_tuned_v2.joblib"
    robust: "models/simple_robust_rf.joblib"
  
  # Scaler path
  scaler_path: "models/scaler_v2.joblib"
  
  # Evaluate adversarial robustness
  evaluate_robustness: true
  
  # Adversarial attacks for robustness testing
  adversarial_attacks:
    enhanced_pgd:
      epsilon: 0.3
      alpha: 0.01
      num_iter: 40
    enhanced_fgsm:
      epsilon: 0.3
  
  # Comparison settings
  generate_comparison_report: true
  calculate_improvement_metrics: true

# Model storage configuration
models:
  save_dir: "models"
  
# Output configuration
output:
  base_dir: "results"
  save_evaluation_results: true
  generate_evaluation_reports: true
  
# Logging configuration
logging:
  level: "INFO"
  save_logs: true
